"use client";
import dynamic from "next/dynamic";
import { useCallback, useEffect, useState } from "react";
import { Activity, ChevronDown, CircleAlert, Clock3, ExternalLink, Layers3, Map as MapIcon, MapPin, Mountain, Pause, Play, RotateCcw, Search, Waves, X } from "lucide-react";
import { layers, situation, timelineEvents } from "@/lib/incident-data";
const FloodMap = dynamic(() => import("./FloodMap"), { ssr: false, loading: () => <div className="map-loading">Loading terrain map…</div> });
const CinematicScene = dynamic(() => import("./CinematicScene"), { ssr: false, loading: () => <div className="map-loading">Building 3D reconstruction…</div> });

export default function Dashboard() {
  const [activeEvent, setActiveEvent] = useState(0); const [playing, setPlaying] = useState(false); const [layersOpen, setLayersOpen] = useState(true); const [aboutOpen, setAboutOpen] = useState(false);
  const [view, setView] = useState<"3d" | "map">("3d");
  const [visibleLayers, setVisibleLayers] = useState<Record<string, boolean>>(() => Object.fromEntries(layers.map((layer) => [layer.id, layer.defaultOn])));
  const event = timelineEvents[activeEvent]; const progress = activeEvent / (timelineEvents.length - 1); const selectEvent = useCallback((index: number) => { setActiveEvent(index); setPlaying(false); }, []);
  useEffect(() => { if (!playing) return; const timer = window.setTimeout(() => { if (activeEvent >= timelineEvents.length - 1) setPlaying(false); else setActiveEvent((v) => v + 1); }, 2200); return () => window.clearTimeout(timer); }, [playing, activeEvent]);
  const statusLabel = event.status === "estimated" ? "Estimated progression" : event.status === "observed" ? "Observed" : "Reported";
  return <main className="dashboard-shell">
    <header className="topbar"><div className="brand"><span className="brand-mark"><Waves size={19} /></span><div><p>NESRA · Situation intelligence</p><h1>Nepal flash flood</h1></div></div><div className="header-status"><span className="live-dot" />{situation.status}<span className="divider" />Verified {situation.verifiedAt}</div><nav><button onClick={() => setAboutOpen(true)}>Methodology</button><button className="icon-button" aria-label="Search"><Search size={18} /></button></nav></header>
    <section className="map-stage">{view === "3d" ? <CinematicScene progress={progress} activeEvent={activeEvent} /> : <FloodMap progress={progress} activeEvent={activeEvent} onSelectEvent={selectEvent} visibleLayers={visibleLayers} />}<div className="map-vignette" />
      <div className="view-switch glass-panel" role="group" aria-label="Visualization view"><button className={view === "3d" ? "active" : ""} onClick={() => setView("3d")}><Mountain size={14} /> 3D reconstruction</button><button className={view === "map" ? "active" : ""} onClick={() => setView("map")}><MapIcon size={14} /> Map</button></div>
      <section className="situation-card glass-panel"><div className="eyebrow"><Activity size={14} /> Situation at a glance</div><div className="metrics"><div><strong>{situation.deaths}</strong><span>reported dead</span></div><div><strong>{situation.missing}</strong><span>reported missing</span></div><div><strong>{situation.districts}</strong><span>districts affected</span></div><div><strong>{situation.roadDamage}</strong><span>road damaged</span></div></div><p><CircleAlert size={13} /> Figures are evolving and may differ by source.</p></section>
      <aside className="event-card glass-panel"><div className="event-card-top"><span className={`evidence-pill ${event.status}`}>{statusLabel}</span><span>{event.district}</span></div><p className="event-time">{event.time} <small>NPT</small></p><h2>{event.place}</h2><h3>{event.summary}</h3><p>{event.detail}</p><a href={event.sourceUrl} target={event.sourceUrl.startsWith("http") ? "_blank" : undefined} rel="noreferrer">{event.source} <ExternalLink size={13} /></a></aside>
      {view === "map" && <aside className={`layer-panel glass-panel ${layersOpen ? "open" : ""}`}><button className="panel-heading" onClick={() => setLayersOpen(!layersOpen)}><span><Layers3 size={16} /> Map layers</span><ChevronDown size={16} /></button>{layersOpen && <div className="layer-list">{layers.map((layer) => <label key={layer.id}><input type="checkbox" checked={visibleLayers[layer.id]} onChange={() => setVisibleLayers((c) => ({ ...c, [layer.id]: !c[layer.id] }))} /><span className="layer-swatch" style={{ background: layer.color }} />{layer.label}</label>)}</div>}</aside>}
      <section className="timeline-panel glass-panel"><div className="timeline-toolbar"><button className="play-button" onClick={() => activeEvent === timelineEvents.length - 1 ? (setActiveEvent(0), setPlaying(true)) : setPlaying(!playing)}>{playing ? <Pause size={18} fill="currentColor" /> : activeEvent === timelineEvents.length - 1 ? <RotateCcw size={18} /> : <Play size={18} fill="currentColor" />}</button><div><span><Clock3 size={13} /> 26 August 2026</span><strong>{event.time} NPT</strong></div><div className="speed">1× speed</div></div><div className="timeline-track"><div className="timeline-progress" style={{ width: `${progress * 100}%` }} />{timelineEvents.map((item, index) => <button key={item.id} className={`timeline-stop ${index <= activeEvent ? "passed" : ""} ${index === activeEvent ? "active" : ""}`} style={{ left: `${index / (timelineEvents.length - 1) * 100}%` }} onClick={() => selectEvent(index)} aria-label={`Go to ${item.place}`}><span /><small>{item.time.split("–")[0]}</small></button>)}</div><div className="timeline-caption"><span><MapPin size={13} /> {event.place}</span><span>Illustrative progression — not a hydraulic forecast</span></div></section>
    </section>
    {aboutOpen && <div className="modal-backdrop" onClick={() => setAboutOpen(false)}><article id="methodology" className="methodology" onClick={(e) => e.stopPropagation()}><button className="close-button" onClick={() => setAboutOpen(false)} aria-label="Close"><X /></button><p className="eyebrow">How to read this reconstruction</p><h2>Evidence before spectacle.</h2><p>The 3D scene illustrates the leading ice-and-rock collapse explanation and anchors flood progression to published reports. It does not present the seismic signal as a confirmed earthquake. Movement and damage between known observations are explanatory reconstruction.</p><div className="method-grid"><div><span className="legend-shape solid" /><strong>Observed or reported</strong><p>Location and timing supported by a cited source.</p></div><div><span className="legend-shape dashed" /><strong>Reconstructed</strong><p>Terrain, water, debris and damage animation used to explain the sequence.</p></div></div><p className="caveat">The animation does not calculate water depth, velocity, building exposure, structural failure, or future arrival time. Do not use it for emergency navigation.</p></article></div>}
  </main>;
}
